CREATE DATABASE IF NOT EXISTS PEDIDOS;
USE PEDIDOS;

DROP TABLE PROVINCIA_ALMACEN;
DROP TABLE ALMACEN_SUMINISTRA;
DROP TABLE ALMACEN;
DROP TABLE ALMACEN_ARTICULO;
DROP TABLE ARTICULO;
DROP TABLE LINEA_PEDIDO;
DROP TABLE PEDIDO;
DROP TABLE CLIENTE;

CREATE OR REPLACE TABLE CLIENTE
(
    NOMBRE VARCHAR(9) NOT NULL, 
    APELLIDOS VARCHAR(25) NOT NULL,
    NIF INT(9) NOT NULL UNIQUE, 
    TELEFONO INT(9) UNSIGNED NOT NULL UNIQUE, 
    EMAIL CHAR(30) UNIQUE, 
    DIRECCION VARCHAR(25) NOT NULL, 
    TARJETA VARCHAR(25),
    TIPO_USUARIO ENUM("ESTANDAR","PREMIUM") NOT NULL,
    FECHA_PREMIUM DATE,
    DESCUENTO INT(4),
    Cod_Cliente VARCHAR(25) NOT NULL UNIQUE PRIMARY KEY
);

CREATE OR REPLACE TABLE PEDIDO
(
    HORA INT(6) NOT NULL, 
    FECHA DATE NOT NULL, 
    NUM_LOCALIZADOR INT(20) PRIMARY KEY, 
    IMPORTE VARCHAR(5) NOT NULL,
    EMAIL VARCHAR(15), 
    Cod_Cliente VARCHAR(20), 
    FOREIGN KEY(Cod_Cliente) REFERENCES CLIENTE(Cod_Cliente)
);

CREATE OR REPLACE TABLE LINEA_PEDIDO
(
    IMPORTE_LINEAL VARCHAR(10) NOT NULL,
    NUMERO_LINEA INT(9) NOT NULL,
    CANTIDAD INT(3) UNSIGNED NOT NULL,
    NUM_REFERENCIA_ARTICULO INT(15),
    NUM_LOCALIZADOR INT(20) NOT NULL,
    FOREIGN KEY(NUM_LOCALIZADOR) REFERENCES PEDIDO(NUM_LOCALIZADOR),
    PRIMARY KEY(NUM_REFERENCIA_ARTICULO, NUM_LOCALIZADOR)
);

CREATE OR REPLACE TABLE ARTICULO
(
   NUM_REFERENCIA_ARTICULO INT(15) PRIMARY KEY,
   NOMBRE_ARTICULO VARCHAR(20) NOT NULL,
   DESCRIPCION VARCHAR(50) NOT NULL,
   PVP INT(4) NOT NULL,
   FOREIGN KEY(NUM_REFERENCIA_ARTICULO) REFERENCES LINEA_PEDIDO(NUM_REFERENCIA_ARTICULO)
);

CREATE OR REPLACE TABLE ALMACEN_ARTICULO
(
   Stock INT(10) UNSIGNED NOT NULL,
   NUM_REFERENCIA_ARTICULO INT(15),
   Cod_Almacen INT(15) NOT NULL,
   FOREIGN KEY(NUM_REFERENCIA_ARTICULO) REFERENCES ARTICULO(NUM_REFERENCIA_ARTICULO),
   PRIMARY KEY(Cod_Almacen, NUM_REFERENCIA_ARTICULO)
);

CREATE OR REPLACE TABLE PROVINCIA
(
    NOMBRE VARCHAR(25),
    Cod_Provincia VARCHAR(25) PRIMARY KEY, 
    NUM_HABITANTES INT, EXTENSION VARCHAR(10),
    Cod_Almacen INT (15)
);

CREATE OR REPLACE TABLE ALMACEN
(
   Cod_Almacen INT(15) PRIMARY KEY,
   NOMBRE_ALMACEN VARCHAR(15) NOT NULL,
   FECHA_APERTURA DATE NOT NULL,
   DIRECCION VARCHAR(25) NOT NULL,
   TELEFONO INT(9) UNSIGNED NOT NULL UNIQUE,
   GERENTE VARCHAR(15) NOT NULL,
   NUM_REFERENCIA_ARTICULO INT(15) NOT NULL UNIQUE,
   FOREIGN KEY(NUM_REFERENCIA_ARTICULO) REFERENCES ALMACEN_ARTICULO(NUM_REFERENCIA_ARTICULO)
);

ALTER TABLE PROVINCIA ADD FOREIGN KEY(Cod_Almacen) REFERENCES ALMACEN(Cod_Almacen);

CREATE OR REPLACE TABLE ALMACEN_SUMINISTRA
(
    Cod_Almacen INT(15) NOT NULL,
    Cod_Almacen_Suministra INT(15) NOT NULL,
    FOREIGN KEY(Cod_Almacen) REFERENCES ALMACEN(Cod_Almacen),
    PRIMARY KEY(Cod_Almacen, Cod_Almacen_Suministra)
);

CREATE OR REPLACE TABLE PROVINCIA_ALMACEN
(
   NOMBRE_PROVINCIA VARCHAR(15) NOT NULL,
   Cod_Provincia INT(15) NOT NULL UNIQUE PRIMARY KEY,
   NUM_HABITANTES INT(8) UNSIGNED NOT NULL,
   EXTENSION VARCHAR (15) NOT NULL,
   Cod_Almacen INT(15) NOT NULL UNIQUE,
   FOREIGN KEY(Cod_Almacen) REFERENCES ALMACEN(Cod_Almacen)
);