CREATE DATABASE IF NOT EXISTS GESTION_CAMPING;

USE GESTION_CAMPING;

CREATE TABLE Cliente(
    IDCLIENTE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    DNI VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(9), 
    FECHA_NACIMIENTO DATE,
    ESTADO ENUM('ACTIVO','SUSPENDIDO', 'BLOQUEADO') NOT NULL,
    COMENTARIOS VARCHAR(300),
    CONSTRAINT DNI_format CHECK (DNI REGEXP '^[0-9]{8}[A-Z]{1}$'),
    CONSTRAINT EMAIL_format CHECK (EMAIL REGEXP '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    CONSTRAINT TELEFONO_format CHECK (TELEFONO REGEXP '^[0-9]{9}$')
);

CREATE TABLE Recurso(
    IDRECURSO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(25) UNIQUE NOT NULL,
    TIPO ENUM('BUNGALOW','BARBACOA', 'PARCELA') NOT NULL,
    CAPACIDAD INT(3) NOT NULL,
    PRECIO INT(5) NOT NULL,
    MINIMO_PERSONAS INT(3) NOT NULL,
    ESTADO ENUM('DISPONIBLE','OCUPADO', 'MANTENIMIENTO') NOT NULL
);

CREATE TABLE Reserva(
    IDRESERVA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT UNSIGNED,
    IDRECURSO INT UNSIGNED,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ESTADO ENUM ('ACTIVA', 'FINALIZADA', 'CANCELADA') NOT NULL,
    PRECIO_TOTAL INT(5) UNSIGNED NOT NULL,
    NUMERO_PERSONAS INT(3) UNSIGNED NOT NULL,
    CONSTRAINT FECHA_VALIDACION CHECK (FECHA_FIN >= FECHA_INICIO),
    FOREIGN KEY (IDCLIENTE) REFERENCES Cliente(IDCLIENTE),
    FOREIGN KEY (IDRECURSO) REFERENCES Recurso(IDRECURSO)
);

CREATE TABLE ACOMPAÑANTE(
    IDACOMPAÑANTE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    IDRESERVA INT UNSIGNED,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    DNI VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(9), 
    CONSTRAINT DNI_format CHECK (DNI REGEXP '^[0-9]{8}[A-Z]{1}$'),
    CONSTRAINT EMAIL_format CHECK (EMAIL REGEXP '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    CONSTRAINT TELEFONO_format CHECK (TELEFONO REGEXP '^[0-9]{9}$'),
    FOREIGN KEY(IDRESERVA) REFERENCES Reserva(IDRESERVA)
);

INSERT INTO Cliente (NOMBRE, APELLIDO, DNI, EMAIL, TELEFONO, FECHA_NACIMIENTO, ESTADO, COMENTARIOS) VALUES
('Juan', 'Pérez', '12345678A', 'juan.perez@example.com', '600123456', '1985-03-15', 'ACTIVO', 'Cliente regular.'),
('Ana', 'García', '87654321B', 'ana.garcia@example.com', '600654321', '1990-07-22', 'SUSPENDIDO', 'Problemas con pagos.'),
('Luis', 'Martínez', '56781234C', 'luis.martinez@example.com', '600987654', '1978-12-05', 'BLOQUEADO', 'Incumplió normas.');

INSERT INTO Recurso (NOMBRE, TIPO, CAPACIDAD, PRECIO, MINIMO_PERSONAS, ESTADO) VALUES
('Bungalow A', 'BUNGALOW', 4, 100, 2, 'DISPONIBLE'),
('Barbacoa Grande', 'BARBACOA', 10, 50, 4, 'OCUPADO'),
('Parcela 5', 'PARCELA', 6, 30, 1, 'MANTENIMIENTO');

INSERT INTO Reserva (IDCLIENTE, IDRECURSO, FECHA_INICIO, FECHA_FIN, ESTADO, PRECIO_TOTAL, NUMERO_PERSONAS) VALUES 
(1, 1, '2024-12-01', '2024-12-05', 'ACTIVA', 400, 4),
(2, 2, '2024-12-10', '2024-12-12', 'FINALIZADA', 100, 6),
(3, 3, '2024-12-15', '2024-12-20', 'CANCELADA', 150, 2);


INSERT INTO ACOMPAÑANTE (IDRESERVA, NOMBRE, APELLIDO, DNI, EMAIL, TELEFONO) VALUES
(1, 'Carlos', 'Hernández', '34567891D', 'carlos.h@example.com', '601234567'),
(1, 'Marta', 'López', '23456789E', 'marta.l@example.com', '602345678'),
(2, 'Elena', 'Ruiz', '45678912F', 'elena.r@example.com', '603456789');
